import { Activity } from "lucide-react";
import { hasAccessToken } from "../../api/client";
import { useHealth, useMissionAlerts, useMissions, usePredictions, useRouteCandidates } from "../../api/queries";
import type { AvailabilityStatus } from "../../api/types";
import { OperationalMap } from "../../components/map/OperationalMap";
import { Alert } from "../../components/ui/Alert";
import { Card } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";
import { ErrorState } from "../../components/ui/ErrorState";
import { LoadingState } from "../../components/ui/LoadingState";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { DecisionReadiness } from "./DecisionReadiness";
import { EnvironmentOverview } from "./EnvironmentOverview";

function SectionTitle({ title, detail }: { title: string; detail?: string }) { return <div className="mb-3 flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-xl font-bold">{title}</h3>{detail && <p className="text-sm text-kurmesh-muted">{detail}</p>}</div>; }
function requestStatus(query: { isError: boolean; data?: unknown }): AvailabilityStatus { return query.isError ? "ERROR" : query.data ? "LIVE" : "UNAVAILABLE"; }

export function DashboardPage() {
  const health = useHealth(); const missions = useMissions(); const mission = missions.data?.items[0]; const predictions = usePredictions(); const routeCandidates = useRouteCandidates(mission?.id); const alerts = useMissionAlerts(mission?.id); const routeStatus = requestStatus(routeCandidates); const alertStatus = requestStatus(alerts);
  return <section aria-labelledby="dashboard-title" className="space-y-8"><div><p className="font-mono text-sm font-bold text-kurmesh-blue">OVERVIEW</p><h2 id="dashboard-title" className="mt-1 text-3xl font-bold">Operational dashboard</h2><p className="mt-2 text-kurmesh-muted">Review operational context and decision readiness from connected services.</p></div>
    {health.isPending ? <LoadingState label="Checking backend availability" /> : health.isError ? <Alert variant="danger" title="Backend unavailable">The backend health check could not be reached.</Alert> : <Alert variant="success" title="Backend reachable">{health.data?.service} is reporting {health.data?.status}.</Alert>}
    {!hasAccessToken() && <Alert variant="info" title="Authenticated data unavailable">Sign in is required before the dashboard can retrieve mission, environment, forecast, route, and alert records.</Alert>}
    <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><SectionTitle title="Mission overview" />{missions.isPending && hasAccessToken() ? <LoadingState label="Loading missions" /> : missions.isError ? <ErrorState title="Mission data unavailable" message="The backend did not return mission records." /> : mission ? <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-kurmesh-muted">Active mission</p><p className="mt-1 text-lg font-bold">{mission.name}</p><p className="mt-1 text-sm text-kurmesh-muted">State: {mission.state}</p>{mission.departure_at && <p className="mt-1 text-sm text-kurmesh-muted">Departure: {new Date(mission.departure_at).toLocaleString()}</p>}</div><StatusBadge status="LIVE" /></div> : <EmptyState title="No mission selected" description="No mission records are currently available." />}</Card><Card variant="highlighted"><SectionTitle title="Next action" /><p className="text-kurmesh-muted">Route-review actions will appear when governed route data is available.</p></Card></div>
    <DecisionReadiness routeStatus={routeStatus} alertStatus={alertStatus} />
    <section><SectionTitle title="Operational view" detail="Neutral base-map foundation" /><OperationalMap /></section><EnvironmentOverview />
    <div className="grid gap-6 xl:grid-cols-2"><section><SectionTitle title="Forecasts" />{predictions.isPending && hasAccessToken() ? <LoadingState label="Loading predictions" /> : predictions.isError ? <ErrorState title="Forecast data unavailable" message="The backend did not return prediction records." /> : !predictions.data?.items.length ? <EmptyState title="No forecasts available" description="No prediction records are currently available." /> : <Card><ul className="space-y-3">{predictions.data.items.map((prediction) => <li key={prediction.id} className="border-b border-kurmesh-border pb-3 last:border-0"><p className="font-semibold">Prediction {prediction.id}</p><p className="text-sm text-kurmesh-muted">Status: {prediction.status}</p>{prediction.reason && <p className="text-sm text-kurmesh-muted">{prediction.reason}</p>}</li>)}</ul></Card>}</section><section><SectionTitle title="Route options" />{routeCandidates.isPending && mission ? <LoadingState label="Loading route candidates" /> : routeCandidates.isError ? <ErrorState title="Route data unavailable" message="The backend did not return route candidates." /> : !mission ? <EmptyState title="No candidate routes" description="Select a mission to retrieve governed route candidates." /> : !routeCandidates.data?.items.length ? <EmptyState title="No candidate routes" description="No route candidates are currently available for this mission." /> : <Card><ul className="space-y-3">{routeCandidates.data.items.map((route) => <li key={route.id} className="border-b border-kurmesh-border pb-3 last:border-0"><p className="font-semibold">Route candidate {route.id}</p><p className="text-sm text-kurmesh-muted">Status: {route.status}</p>{route.distance_nm !== null && <p className="text-sm text-kurmesh-muted">Distance: {route.distance_nm} nautical miles</p>}{route.estimated_duration_hours !== null && <p className="text-sm text-kurmesh-muted">Duration: {route.estimated_duration_hours} hours</p>}</li>)}</ul></Card>}</section></div>
    <div className="grid gap-6 xl:grid-cols-3"><section><SectionTitle title="Alerts" />{alerts.isPending && mission ? <LoadingState label="Loading alerts" /> : alerts.isError ? <ErrorState title="Alert data unavailable" message="The backend did not return alerts." /> : !mission ? <EmptyState title="No active alerts available." description="Select a mission to retrieve its alerts." /> : !alerts.data?.items.length ? <EmptyState title="No active alerts available." description="No alerts are currently available for this mission." /> : <Card><ul className="space-y-3">{alerts.data.items.map((alert) => <li key={alert.id} className="border-b border-kurmesh-border pb-3 last:border-0"><p className="font-semibold">{alert.title}</p><p className="text-sm text-kurmesh-muted">{alert.severity} · {alert.status}</p><p className="text-sm text-kurmesh-muted">{alert.message}</p></li>)}</ul></Card>}</section><section className="xl:col-span-2"><SectionTitle title="Mission timeline" /><EmptyState title="No mission events available." description="Timeline events will appear when a mission is selected." icon={<Activity aria-hidden="true" />} /></section></div>
    <section><SectionTitle title="Data and provenance status" /><Card><p className="text-kurmesh-muted">Source and provenance records are restricted to the backend's authorized provenance contract and are not loaded into this dashboard without the required role.</p></Card></section></section>;
}
