import { Activity } from "lucide-react";
import { OperationalMap } from "../../components/map/OperationalMap";
import { Card } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { DecisionReadiness } from "./DecisionReadiness";
import { EnvironmentOverview } from "./EnvironmentOverview";

function SectionTitle({ title, detail }: { title: string; detail?: string }) { return <div className="mb-3 flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-xl font-bold">{title}</h3>{detail && <p className="text-sm text-kurmesh-muted">{detail}</p>}</div>; }
export function DashboardPage() { return <section aria-labelledby="dashboard-title" className="space-y-8"><div><p className="font-mono text-sm font-bold text-kurmesh-blue">OVERVIEW</p><h2 id="dashboard-title" className="mt-1 text-3xl font-bold">Operational dashboard</h2><p className="mt-2 text-kurmesh-muted">Review operational context and decision readiness as services become available.</p></div><div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><SectionTitle title="Mission overview" /><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-kurmesh-muted">Active mission</p><p className="mt-1 text-lg font-bold">No mission selected</p></div><StatusBadge status="UNAVAILABLE" /></div><p className="mt-4 text-sm text-kurmesh-muted">Mission identifier and operational state will appear when mission services are connected.</p></Card><Card variant="highlighted"><SectionTitle title="Next action" /><p className="text-kurmesh-muted">Route-review actions will appear here when decision inputs are available.</p></Card></div><DecisionReadiness /><section><SectionTitle title="Operational view" detail="Neutral base-map foundation" /><OperationalMap /></section><EnvironmentOverview /><div className="grid gap-6 xl:grid-cols-2"><section><SectionTitle title="Forecasts" /><Card><div className="grid gap-4 md:grid-cols-2"><EmptyState title="Sea Ice Forecast" description="Validated forecast data will appear once available." /><EmptyState title="Iceberg Trajectory" description="Validated trajectory data will appear once available." /></div></Card></section><section><SectionTitle title="Route options" /><EmptyState title="No candidate routes" description="Candidate routes will eventually include distance, travel time, exposure, constraints, and review status after the routing service is connected." /></section></div><div className="grid gap-6 xl:grid-cols-3"><section><SectionTitle title="Alerts" /><EmptyState title="No active alerts available." description="Alert information will appear when monitoring services are connected." /></section><section className="xl:col-span-2"><SectionTitle title="Mission timeline" /><EmptyState title="No mission events available." description="Timeline events will appear when a mission is selected." icon={<Activity aria-hidden="true" />} /></section></div><section><SectionTitle title="Data and provenance status" /><Card><p className="text-kurmesh-muted">Provider, timestamp, freshness, and provenance details will appear here as connected data is reviewed.</p></Card></section></section>; }
