import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, render, screen } from "@testing-library/react";
import "@testing-library/jest-dom/vitest";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DashboardPage } from "./DashboardPage";
vi.mock("../../components/map/OperationalMap", () => ({ OperationalMap: () => <div aria-label="Operational map" /> }));
function response(body: unknown) { return new Response(JSON.stringify(body), { status: 200, headers: { "Content-Type": "application/json" } }); }
beforeEach(() => { localStorage.setItem("kurmesh.accessToken", "test-token"); vi.stubGlobal("fetch", vi.fn((input: string) => { if (input.endsWith("/health/live")) return Promise.resolve(response({ status: "LIVE", service: "kurmesh-api" })); if (input.endsWith("/missions")) return Promise.resolve(response({ items: [{ id: "mission-1", name: "Verified mission", state: "PLANNING", vessel_id: null, departure_at: null }] })); if (input.endsWith("/environment/observations")) return Promise.resolve(response({ items: [{ id: "environment-1", source_id: "source", observation_type: "weather", status: "DEGRADED", value: null, units: "none", quality: null, resolution: null, retrieved_at: "2026-01-01T00:00:00Z", valid_from: null, valid_to: null, location: null }] })); if (input.endsWith("/predictions")) return Promise.resolve(response({ items: [{ id: "prediction-1", status: "MODEL_UNAVAILABLE", reason: "Model artifact unavailable", output: null }] })); if (input.endsWith("/route-candidates")) return Promise.resolve(response({ items: [{ id: "route-1", mission_id: "mission-1", prediction_id: null, version: 1, status: "READY", geometry: null, distance_nm: 15, estimated_duration_hours: 3, risk_score: null, risk_components: {}, environmental_snapshot: {}, algorithm_version: "v1", metadata: {} }] })); if (input.endsWith("/alerts")) return Promise.resolve(response({ items: [{ id: "alert-1", mission_id: "mission-1", severity: "HIGH", category: "NAVIGATION", title: "Backend alert", message: "Provider supplied alert", status: "OPEN", acknowledged_at: null }] })); return Promise.reject(new Error(`Unexpected request: ${input}`)); })); });
afterEach(() => { cleanup(); localStorage.clear(); vi.unstubAllGlobals(); });
describe("DashboardPage", () => { it("renders connected backend records and their actual states", async () => { render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><DashboardPage /></QueryClientProvider>); expect(await screen.findByText("Verified mission")).toBeInTheDocument(); expect(screen.getByText("Prediction prediction-1")).toBeInTheDocument(); expect(await screen.findByText("Distance: 15 nautical miles")).toBeInTheDocument(); expect(screen.getByText("Backend alert")).toBeInTheDocument(); expect(screen.getByText("Provider supplied alert")).toBeInTheDocument(); expect(screen.queryByText("Antarctic Research Mission 01")).not.toBeInTheDocument(); }); });
