import { hasAccessToken } from "../../api/client";
import { useEnvironmentObservations } from "../../api/queries";
import type { EnvironmentObservation } from "../../api/types";
import { Card } from "../../components/ui/Card";
import { ErrorState } from "../../components/ui/ErrorState";
import { LoadingState } from "../../components/ui/LoadingState";
import { StatusBadge } from "../../components/ui/StatusBadge";
const categories = [{ label: "Sea Ice", matches: (type: string) => type.startsWith("sea_ice") }, { label: "Weather", matches: (type: string) => ["weather", "wind", "air_temperature", "sea_level_pressure"].includes(type) }, { label: "Ocean", matches: (type: string) => type.startsWith("ocean_") || type.startsWith("sea_water_") }, { label: "Iceberg", matches: (type: string) => type.startsWith("iceberg") }];
function EnvironmentCard({ label, observation }: { label: string; observation?: EnvironmentObservation }) { if (!hasAccessToken()) return <Card><div className="flex items-center justify-between gap-3"><h4 className="font-bold">{label}</h4><StatusBadge status="UNAVAILABLE" /></div><p className="mt-3 text-sm text-kurmesh-muted">Authentication is required to retrieve provider data.</p></Card>; if (!observation) return <Card><div className="flex items-center justify-between gap-3"><h4 className="font-bold">{label}</h4><StatusBadge status="UNAVAILABLE" /></div><p className="mt-3 text-sm text-kurmesh-muted">No current data available.</p></Card>; return <Card><div className="flex items-center justify-between gap-3"><h4 className="font-bold">{label}</h4><StatusBadge status={observation.status} /></div><p className="mt-3 text-sm text-kurmesh-muted">{observation.observation_type.replaceAll("_", " ")}</p><p className="mt-2 border-t border-kurmesh-border pt-2 text-xs text-kurmesh-muted">Retrieved {new Date(observation.retrieved_at).toLocaleString()}</p></Card>; }
export function EnvironmentOverview() { const observations = useEnvironmentObservations(); return <section aria-labelledby="environment-title"><h3 id="environment-title" className="mb-3 text-xl font-bold">Environmental status</h3>{observations.isPending && hasAccessToken() ? <LoadingState label="Loading environmental observations" /> : observations.isError ? <ErrorState title="Environmental observations unavailable" message="The backend did not return environmental observations." /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{categories.map(({ label, matches }) => <EnvironmentCard key={label} label={label} observation={observations.data?.items.find((item) => matches(item.observation_type))} />)}</div>}</section>; }
