import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom/vitest";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { RouteReviewPanel } from "./RouteReviewPanel";

const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
const candidate = { id: "candidate-1", mission_id: "mission-1", prediction_id: null, version: 2, status: "READY", geometry: { type: "LineString" as const, coordinates: [[10, -70], [12, -71]] as [number, number][] }, distance_nm: 125, estimated_duration_hours: null, risk_score: null, risk_components: { sea_ice: "LIVE" }, environmental_snapshot: { source: "backend" }, algorithm_version: "routing-v1", metadata: { data_confidence: "verified" } };
const route = { id: "route-1", route_candidate_id: candidate.id, status: "UNDER_REVIEW", geometry: candidate.geometry, metadata: {} };

function renderPanel(props: Partial<Parameters<typeof RouteReviewPanel>[0]> = {}) { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><RouteReviewPanel missionId="mission-1" candidate={candidate} {...props} /></QueryClientProvider>); }
beforeEach(() => localStorage.setItem("kurmesh.accessToken", "test-token"));
afterEach(() => { cleanup(); localStorage.clear(); vi.unstubAllGlobals(); });

describe("RouteReviewPanel", () => {
  it("shows a truthful empty review state when no candidate is selected", () => { renderPanel({ candidate: undefined }); expect(screen.getByText("No route selected")).toBeInTheDocument(); });
  it("shows backend route facts without fabricating unavailable metrics", () => { renderPanel({ route }); expect(screen.getByText("Route Candidate v2")).toBeInTheDocument(); expect(screen.getByText("125 nautical miles")).toBeInTheDocument(); expect(screen.getAllByText("Unavailable").length).toBeGreaterThan(0); expect(screen.getByText("verified")).toBeInTheDocument(); });
  it("opens a READY candidate for human review through the existing route API", async () => { vi.stubGlobal("fetch", vi.fn((input: string, init?: RequestInit) => input.endsWith("/routes") && init?.method === "POST" ? Promise.resolve(response({ ...route, status: "DRAFT" }, 201)) : Promise.resolve(response({ items: [] })))); renderPanel(); fireEvent.click(screen.getByRole("button", { name: "Open human review" })); await waitFor(() => expect(vi.mocked(fetch)).toHaveBeenCalledWith("/api/v1/missions/mission-1/routes", expect.objectContaining({ method: "POST", headers: expect.objectContaining({ Authorization: "Bearer test-token" }) }))); expect(await screen.findByText("Route opened for governed human review.")).toBeInTheDocument(); });
  it("records a review using the backend decision contract", async () => { vi.stubGlobal("fetch", vi.fn((input: string, init?: RequestInit) => input.endsWith("/reviews") && init?.method === "POST" ? Promise.resolve(response({ id: "review-1", route_id: route.id, decision: "APPROVED", comments: null }, 201)) : Promise.resolve(response({ items: [] })))); renderPanel({ route }); fireEvent.change(screen.getByLabelText("Review comments"), { target: { value: "Reviewed by operator." } }); fireEvent.click(screen.getByRole("button", { name: "Review" })); await waitFor(() => expect(vi.mocked(fetch)).toHaveBeenCalledWith(`/api/v1/routes/${route.id}/reviews`, expect.objectContaining({ method: "POST" }))); expect(await screen.findByText("Human review recorded: APPROVED.")).toBeInTheDocument(); });
  it("records rejection through a human review rather than a fabricated route outcome", async () => { vi.stubGlobal("fetch", vi.fn((input: string, init?: RequestInit) => input.endsWith("/reviews") && init?.method === "POST" ? Promise.resolve(response({ id: "review-1", route_id: route.id, decision: "REJECTED", comments: null }, 201)) : Promise.resolve(response({ items: [] })))); renderPanel({ route }); fireEvent.click(screen.getByRole("button", { name: "Reject" })); await waitFor(() => expect(vi.mocked(fetch)).toHaveBeenCalledWith(`/api/v1/routes/${route.id}/reviews`, expect.objectContaining({ method: "POST" }))); expect(await screen.findByText("Human review recorded: REJECTED.")).toBeInTheDocument(); });
  it("submits approval only to the existing human approval endpoint", async () => { vi.stubGlobal("fetch", vi.fn((input: string, init?: RequestInit) => input.endsWith("/approvals") && init?.method === "POST" ? Promise.resolve(response({ id: "approval-1", route_id: route.id, decision: "APPROVED" }, 201)) : Promise.resolve(response({ items: [] })))); renderPanel({ route }); fireEvent.click(screen.getByRole("button", { name: "Approve Route" })); await waitFor(() => expect(vi.mocked(fetch)).toHaveBeenCalledWith(`/api/v1/routes/${route.id}/approvals`, expect.objectContaining({ method: "POST" }))); expect(await screen.findByText("Human approval decision recorded: APPROVED.")).toBeInTheDocument(); });
  it("shows the backend invalid-transition or authorization failure without bypassing it", async () => { vi.stubGlobal("fetch", vi.fn((input: string, init?: RequestInit) => input.endsWith("/approvals") && init?.method === "POST" ? Promise.resolve(response({ error: { code: "ROUTE_NOT_UNDER_REVIEW", message: "A route must be under review before approval" } }, 409)) : Promise.resolve(response({ items: [] })))); renderPanel({ route }); fireEvent.click(screen.getByRole("button", { name: "Approve Route" })); expect(await screen.findByText("A route must be under review before approval")).toBeInTheDocument(); });
  it("surfaces reviewer authorization denial without offering a fallback", async () => { vi.stubGlobal("fetch", vi.fn((input: string, init?: RequestInit) => input.endsWith("/reviews") && init?.method === "POST" ? Promise.resolve(response({ error: { code: "FORBIDDEN", message: "Reviewer role is required" } }, 403)) : Promise.resolve(response({ items: [] })))); renderPanel({ route }); fireEvent.click(screen.getByRole("button", { name: "Review" })); expect(await screen.findByText("Reviewer role is required")).toBeInTheDocument(); });
});
