import { useState, type FormEvent } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { ApiError } from "../../api/client";
import { createRoute, createRouteApproval, createRouteReview } from "../../api/routes";
import type { Route, RouteCandidate } from "../../api/types";
import { Alert } from "../../components/ui/Alert";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";

const errorMessage = (error: unknown) => error instanceof ApiError ? error.message : "The governed workflow action could not be completed.";

export function RouteReviewPanel({ missionId, candidate, route }: { missionId: string; candidate?: RouteCandidate; route?: Route }) {
  const client = useQueryClient(); const [comments, setComments] = useState(""); const [message, setMessage] = useState<string | null>(null);
  const refresh = () => { void client.invalidateQueries({ queryKey: ["missions", missionId, "routes"] }); };
  const routeCreation = useMutation({ mutationFn: () => createRoute(missionId, candidate!.id), onSuccess: () => { setMessage("Route opened for governed human review."); refresh(); }, onError: (error) => setMessage(errorMessage(error)) });
  const review = useMutation({ mutationFn: (decision: "APPROVED" | "REJECTED" | "CHANGES_REQUESTED") => createRouteReview(route!.id, decision, comments), onSuccess: (result) => { setMessage(`Human review recorded: ${result.decision}.`); refresh(); }, onError: (error) => setMessage(errorMessage(error)) });
  const approval = useMutation({ mutationFn: (decision: "APPROVED" | "REJECTED") => createRouteApproval(route!.id, decision, comments), onSuccess: (result) => { setMessage(`Human approval decision recorded: ${result.decision}.`); refresh(); }, onError: (error) => setMessage(errorMessage(error)) });
  if (!candidate) return <EmptyState title="No route selected" description="Select a backend route candidate to view its governed review workflow." />;
  if (!route) return <Card><h3 className="text-xl font-bold">Human Review</h3><p className="mt-2 text-sm text-kurmesh-muted">Candidate v{candidate.version} is {candidate.status}. A persisted route is required before a human review can be recorded.</p>{message && <Alert className="mt-4" variant="info" title="Governed route workflow">{message}</Alert>}<div className="mt-5"><Button loading={routeCreation.isPending} disabled={candidate.status !== "READY"} onClick={() => routeCreation.mutate()}>Open human review</Button>{candidate.status !== "READY" && <p className="mt-2 text-xs text-kurmesh-muted">Only backend READY candidates may enter review.</p>}</div></Card>;
  function submit(event: FormEvent<HTMLFormElement>, action: "review" | "reject" | "approve") { event.preventDefault(); if (action === "review") review.mutate("APPROVED"); else if (action === "reject") review.mutate("REJECTED"); else approval.mutate("APPROVED"); }
  const busy = review.isPending || approval.isPending;
  return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold tracking-wide text-kurmesh-blue">HUMAN DECISION POINT</p><h3 className="mt-1 text-xl font-bold">Route Candidate v{candidate.version}</h3></div><Badge>{route.status}</Badge></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-kurmesh-muted">Route identity</dt><dd className="break-all font-semibold">{route.id}</dd></div><div><dt className="text-kurmesh-muted">Candidate status</dt><dd className="font-semibold">{candidate.status}</dd></div><div><dt className="text-kurmesh-muted">Distance</dt><dd className="font-semibold">{candidate.distance_nm === null ? "Unavailable" : `${candidate.distance_nm} nautical miles`}</dd></div><div><dt className="text-kurmesh-muted">Risk information</dt><dd className="font-semibold">{Object.keys(candidate.risk_components).length ? "Available in route details" : "Unavailable"}</dd></div><div><dt className="text-kurmesh-muted">Data confidence</dt><dd className="font-semibold">{typeof candidate.metadata.data_confidence === "string" || typeof candidate.metadata.data_confidence === "number" ? String(candidate.metadata.data_confidence) : "Unavailable"}</dd></div><div><dt className="text-kurmesh-muted">Created / updated time</dt><dd className="font-semibold">Unavailable</dd></div></dl><form className="mt-5 space-y-4" onSubmit={(event) => submit(event, "review")}><label className="block text-sm font-semibold">Review comments <span className="font-normal text-kurmesh-muted">(optional)</span><textarea aria-label="Review comments" className="mt-2 min-h-24 w-full rounded-lg border border-kurmesh-border p-3" value={comments} onChange={(event) => setComments(event.target.value)} disabled={busy} maxLength={5000} /></label>{message && <Alert variant="info" title="Governed route workflow">{message}</Alert>}<div className="flex flex-wrap justify-end gap-3"><Button variant="danger" loading={review.isPending} disabled={busy} onClick={(event) => submit(event as unknown as FormEvent<HTMLFormElement>, "reject")}>Reject</Button><Button type="submit" loading={review.isPending} disabled={busy}>Review</Button><Button variant="success" loading={approval.isPending} disabled={busy} onClick={(event) => submit(event as unknown as FormEvent<HTMLFormElement>, "approve")}>Approve Route</Button></div></form><p className="mt-4 text-xs text-kurmesh-muted">Review and approval are separate human actions. The backend enforces operator authorization and reviewer–approver separation.</p></Card>;
}
