import { useEffect, useMemo, useRef, useState } from "react";
import { Map, type GeoJSONSource } from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import type { RouteCandidate } from "../../api/types";
import { ErrorState } from "../ui/ErrorState";
import { LoadingState } from "../ui/LoadingState";
import { MapControls } from "./MapControls";
import { MapLegend } from "./MapLegend";
import { antarcticView, neutralPolarStyle } from "./mapStyles";
import type { OperationalLayer } from "./types";

const routeSourceId = "candidate-routes";
const selectedRouteSourceId = "selected-candidate-route";
function features(routes: RouteCandidate[]) { return { type: "FeatureCollection" as const, features: routes.filter((route) => route.geometry).map((route) => ({ type: "Feature" as const, properties: { id: route.id }, geometry: route.geometry! })) }; }

export function OperationalMap({ layers = [], routes = [], selectedRouteId }: { layers?: OperationalLayer[]; routes?: RouteCandidate[]; selectedRouteId?: string }) {
  const container = useRef<HTMLDivElement>(null); const map = useRef<Map | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const routeFeatures = useMemo(() => features(routes), [routes]); const selectedFeatures = useMemo(() => features(routes.filter((route) => route.id === selectedRouteId)), [routes, selectedRouteId]);
  useEffect(() => { if (!container.current) return; try { const instance = new Map({ container: container.current, style: neutralPolarStyle, center: antarcticView.center, zoom: antarcticView.zoom, maxBounds: antarcticView.maxBounds, attributionControl: false }); map.current = instance; instance.on("load", () => { instance.resize(); setState("ready"); }); instance.on("error", () => setState("error")); const observer = new ResizeObserver(() => instance.resize()); observer.observe(container.current); return () => { observer.disconnect(); instance.remove(); map.current = null; }; } catch { setState("error"); } }, []);
  useEffect(() => { const instance = map.current; if (state !== "ready" || !instance) return; if (!instance.getSource(routeSourceId)) { instance.addSource(routeSourceId, { type: "geojson", data: routeFeatures }); instance.addLayer({ id: "candidate-routes-line", type: "line", source: routeSourceId, paint: { "line-color": "#2176AE", "line-width": 3, "line-opacity": 0.8 } }); instance.addSource(selectedRouteSourceId, { type: "geojson", data: selectedFeatures }); instance.addLayer({ id: "selected-candidate-route-line", type: "line", source: selectedRouteSourceId, paint: { "line-color": "#0B3C5D", "line-width": 5 } }); } else { const source = instance.getSource(routeSourceId); const selectedSource = instance.getSource(selectedRouteSourceId); if (source && source.type === "geojson") (source as GeoJSONSource).setData(routeFeatures); if (selectedSource && selectedSource.type === "geojson") (selectedSource as GeoJSONSource).setData(selectedFeatures); } const selected = routes.find((route) => route.id === selectedRouteId)?.geometry; if (selected?.coordinates.length) { const longitudes = selected.coordinates.map(([longitude]) => longitude); const latitudes = selected.coordinates.map(([, latitude]) => latitude); instance.fitBounds([[Math.min(...longitudes), Math.min(...latitudes)], [Math.max(...longitudes), Math.max(...latitudes)]], { padding: 56, maxZoom: 7, duration: 0 }); } }, [routeFeatures, routes, selectedFeatures, selectedRouteId, state]);
  const reset = () => map.current?.jumpTo({ center: antarcticView.center, zoom: antarcticView.zoom }); const hasGeometry = routeFeatures.features.length > 0;
  return <section aria-label="Operational map" className="relative min-h-[26rem] overflow-hidden rounded-card border border-kurmesh-border bg-kurmesh-polar"><div ref={container} className="absolute inset-0" />{state === "loading" && <div className="absolute inset-0 z-20 bg-kurmesh-polar/90"><LoadingState label="Preparing Antarctic map foundation" /></div>}{state === "error" && <div className="absolute inset-4 z-20"><ErrorState title="Operational map unavailable" message="The map foundation could not be initialized. No operational layers are displayed." /></div>}{state !== "error" && <><MapControls onZoomIn={() => map.current?.zoomIn()} onZoomOut={() => map.current?.zoomOut()} onReset={reset} /><MapLegend layers={layers} /><div className="absolute left-4 top-4 z-10 max-w-xs rounded-lg border border-kurmesh-border bg-white/95 p-3 text-sm text-kurmesh-muted shadow-card"><p className="font-bold text-kurmesh-text">Antarctic operational map</p><p className="mt-1">{hasGeometry ? "Candidate route geometry from the selected mission is shown." : "No candidate route geometry is available for the selected mission."}</p></div></>}</section>;
}
