import { Anchor, ArrowRight, CheckCircle2, ChevronRight, ClipboardList, Database, Layers3, LockKeyhole, MapPinned, Radio, ShipWheel, Sparkles } from "lucide-react";
import "./documentation.css";

type Status = "IMPLEMENTED" | "IN DEVELOPMENT" | "FUTURE";
type Api = { method: string; path: string; purpose: string; auth: string; status: Status; request?: string; response?: string };
const id = "<uuid>";
const noBody = "No request body";
const apis: Api[] = [
  ["GET","/health/live","Dependency-free liveness probe.","Public","IMPLEMENTED",noBody,'{ "status": "LIVE", "service": "kurmesh-api" }'],
  ["GET","/health","Checks database and Redis connectivity.","Public","IMPLEMENTED",noBody,'{ "status": "LIVE", "services": { "database": { "status": "LIVE" } } }'],
  ["GET","/health/ready","Readiness probe; 503 until dependencies are ready.","Public","IMPLEMENTED",noBody,'{ "status": "UNAVAILABLE", "services": { "redis": { "status": "UNAVAILABLE" } } }'],
  ["POST","/auth/register","Creates a non-privileged user and token.","Public","IMPLEMENTED",'{ "email": "operator@example.org", "password": "secure-password", "full_name": "A. Operator" }','{ "user": { "id": "'+id+'", "roles": ["user"] }, "access_token": "…" }'],
  ["POST","/auth/login","Authenticates a user and issues a Bearer token.","Public","IMPLEMENTED",'{ "email": "operator@example.org", "password": "secure-password" }','{ "access_token": "…", "token_type": "Bearer" }'],
  ["GET","/auth/me","Returns the authenticated user profile.","Bearer","IMPLEMENTED",noBody,'{ "id": "'+id+'", "roles": ["user"] }'],
  ["GET","/users","Lists user profiles.","Bearer · admin","IMPLEMENTED",noBody,'{ "items": [{ "id": "'+id+'", "email": "operator@example.org" }], "limit": 50, "offset": 0 }'],
  ["GET","/users/me","Returns the caller’s safe profile.","Bearer","IMPLEMENTED",noBody,'{ "id": "'+id+'", "full_name": "A. Operator" }'],
  ["GET","/users/{user_id}","Gets own profile; admins may retrieve others.","Bearer","IMPLEMENTED",noBody,'{ "id": "'+id+'", "roles": ["user"] }'],
  ["GET · POST","/vessels","Lists or creates vessel records.","Bearer","IMPLEMENTED",'{ "name": "Polar Scout", "vessel_type": "research", "specifications": {} }','{ "id": "'+id+'", "name": "Polar Scout", "vessel_type": "research" }'],
  ["GET · PATCH · DELETE","/vessels/{vessel_id}","Reads, replaces or deletes a vessel record.","Bearer","IMPLEMENTED",'{ "name": "Polar Scout", "vessel_type": "research", "specifications": {} }','{ "id": "'+id+'", "name": "Polar Scout" }'],
  ["GET · POST","/missions","Lists missions or creates one, optionally linked to a vessel.","Bearer","IMPLEMENTED",'{ "name": "Antarctic transit", "vessel_id": "'+id+'" }','{ "id": "'+id+'", "name": "Antarctic transit", "state": "DRAFT" }'],
  ["GET · PATCH · DELETE","/missions/{mission_id}","Reads or manages a mission; mutations require owner or admin.","Bearer","IMPLEMENTED",'{ "name": "Updated transit" }','{ "id": "'+id+'", "state": "DRAFT" }'],
  ["POST","/missions/{mission_id}/transition","Applies a valid state change; cannot approve a route.","Bearer · owner/admin","IMPLEMENTED",'{ "state": "PLANNING" }','{ "id": "'+id+'", "state": "PLANNING" }'],
  ["POST","/missions/{mission_id}/constraints","Records an explicitly supplied mission constraint.","Bearer · owner/admin","IMPLEMENTED",'{ "constraint_type": "max_wind", "value": { "knots": 30 } }','{ "id": "'+id+'", "constraint_type": "max_wind" }'],
  ["GET · POST","/environment/sources","Lists or records environmental-source metadata.","Bearer","IMPLEMENTED",'{ "provider": "NOAA", "source": "GFS", "metadata": {} }','{ "id": "'+id+'", "provider": "NOAA", "source": "GFS" }'],
  ["GET · PATCH","/environment/sources/{source_id}","Reads or updates source metadata.","Bearer","IMPLEMENTED",'{ "url": "https://example.invalid/source" }','{ "id": "'+id+'", "provider": "NOAA" }'],
  ["GET · POST","/environment/observations","Lists filtered observations or stores supplied observation metadata.","Bearer","IMPLEMENTED",'{ "source_id": "'+id+'", "observation_type": "weather", "status": "LIVE", "value": { "wind_kn": 18 }, "units": "kn", "retrieved_at": "2026-09-26T00:00:00Z" }','{ "id": "'+id+'", "status": "LIVE", "value": { "wind_kn": 18 } }'],
  ["GET","/environment/observations/{observation_id}","Retrieves one environmental observation.","Bearer","IMPLEMENTED",noBody,'{ "id": "'+id+'", "observation_type": "weather", "status": "LIVE" }'],
  ["GET · POST","/models","Lists or records model-version metadata; no model execution.","Bearer","IMPLEMENTED",'{ "name": "iceberg-demo", "version": "1.0", "status": "REVIEWED", "metadata": {} }','{ "id": "'+id+'", "name": "iceberg-demo", "status": "REVIEWED" }'],
  ["GET · PATCH","/models/{model_id}","Reads or updates model-version metadata.","Bearer","IMPLEMENTED",'{ "status": "REVIEWED" }','{ "id": "'+id+'", "status": "REVIEWED" }'],
  ["GET · POST","/models/{model_id}/artifacts","Lists or records artifact references and SHA-256.","Bearer","IMPLEMENTED",'{ "path": "models/demo.bin", "sha256": "64-hex-character-sha256", "artifact_type": "model" }','{ "id": "'+id+'", "artifact_type": "model" }'],
  ["GET","/models/{model_id}/artifacts/{artifact_id}","Retrieves a model-artifact record.","Bearer","IMPLEMENTED",noBody,'{ "id": "'+id+'", "path": "models/demo.bin" }'],
  ["GET · POST","/predictions","Lists or records prediction requests; POST never runs inference.","Bearer","IMPLEMENTED",'{ "mission_id": "'+id+'", "model_version_id": "'+id+'", "status": "PENDING" }','{ "id": "'+id+'", "status": "PENDING", "output": null }'],
  ["GET","/predictions/{prediction_id}","Retrieves a prediction record for an accessible mission.","Bearer","IMPLEMENTED",noBody,'{ "id": "'+id+'", "status": "MODEL_UNAVAILABLE" }'],
  ["POST","/demo/ml/iceberg/predict","Runs the offline demo-only 24-hour iceberg displacement model.","Public","IMPLEMENTED",'{ "current_x_m": 1, "current_y_m": 2, "previous_dx_m": 0, "previous_dy_m": 0, "previous_delta_longitude_deg": 0, "day_of_year_sin": 0, "day_of_year_cos": 1 }','{ "status": "OFFLINE_DEMO_ONLY", "forecast_horizon": "24 hours", "prediction": {} }'],
  ["GET · POST","/missions/{mission_id}/route-candidates","Lists or records submitted candidates; never calculates a route.","Bearer · owner/admin","IMPLEMENTED",'{ "version": 1, "geometry": { "type": "LineString", "coordinates": [[0,0],[1,1]] }, "algorithm_version": "submitted-v1" }','{ "id": "'+id+'", "status": "DRAFT", "geometry": { "type": "LineString" } }'],
  ["GET · PATCH · DELETE","/route-candidates/{candidate_id}","Reads, updates or deletes an unselected candidate.","Bearer · owner/admin","IMPLEMENTED",'{ "status": "READY" }','{ "id": "'+id+'", "status": "READY" }'],
  ["GET · POST","/missions/{mission_id}/routes","Lists routes or selects a READY candidate as DRAFT.","Bearer · owner/admin","IMPLEMENTED",'{ "route_candidate_id": "'+id+'", "metadata": {} }','{ "id": "'+id+'", "status": "DRAFT" }'],
  ["GET · PATCH","/routes/{route_id}","Reads or updates a route; direct approval is rejected.","Bearer · owner/admin","IMPLEMENTED",'{ "status": "ACTIVE" }','{ "id": "'+id+'", "status": "ACTIVE" }'],
  ["GET","/routes","Lists routes accessible to the caller.","Bearer","IMPLEMENTED",noBody,'{ "items": [{ "id": "'+id+'", "status": "UNDER_REVIEW" }] }'],
  ["POST","/routes/{route_id}/reviews","Records an independent governed route review.","Bearer · operator/admin","IMPLEMENTED",'{ "decision": "APPROVED", "comments": "Reviewed" }','{ "id": "'+id+'", "decision": "APPROVED" }'],
  ["POST","/routes/{route_id}/approvals","Records separate approval after an approved review.","Bearer · operator/admin","IMPLEMENTED",'{ "decision": "APPROVED", "comments": "Approved" }','{ "id": "'+id+'", "decision": "APPROVED" }'],
  ["POST","/routes/{route_id}/review","Legacy review endpoint using RECOMMENDED-style decisions.","Bearer · independent operator/admin","IMPLEMENTED",'{ "decision": "RECOMMENDED", "reason": "Reviewed" }','{ "id": "'+id+'", "decision": "RECOMMENDED" }'],
  ["POST","/routes/{route_id}/approval","Legacy approval endpoint requiring affirmative independent review.","Bearer · operator/admin","IMPLEMENTED",'{ "decision": "APPROVED", "reason": "Approved" }','{ "id": "'+id+'", "decision": "APPROVED" }'],
  ["GET · POST","/missions/{mission_id}/alerts","Lists or creates mission-scoped alerts.","Bearer · owner/admin","IMPLEMENTED",'{ "mission_id": "'+id+'", "severity": "HIGH", "category": "weather", "title": "Wind", "message": "Review required" }','{ "id": "'+id+'", "status": "OPEN" }'],
  ["POST","/alerts/{alert_id}/acknowledgement","Acknowledges or resolves a mission alert.","Bearer · owner/admin","IMPLEMENTED",'{ "status": "ACKNOWLEDGED" }','{ "id": "'+id+'", "status": "ACKNOWLEDGED" }'],
  ["GET","/alerts","Lists alerts for missions accessible to the caller.","Bearer","IMPLEMENTED",noBody,'{ "items": [{ "id": "'+id+'", "severity": "HIGH" }] }'],
  ["GET · POST","/provenance","Lists provenance (admin) or records supplied provenance (operator/admin).","Bearer · role-dependent","IMPLEMENTED",'{ "entity_type": "EnvironmentObservation", "entity_id": "'+id+'", "source_type": "provider", "source_reference": "reference" }','{ "id": "'+id+'", "entity_type": "EnvironmentObservation" }'],
  ["GET · POST","/simulation","Lists records or queues a PENDING persistence request; no worker executes it.","Bearer","IN DEVELOPMENT",'{ "mission_id": "'+id+'", "scenario": {} }','{ "id": "'+id+'", "status": "PENDING", "is_simulation": true }'],
  ["GET","/audit","Lists append-oriented audit events; no audit mutation API exists.","Bearer · admin","IMPLEMENTED",noBody,'{ "items": [{ "event_type": "MISSION_CREATED", "entity_type": "Mission" }] }']
].map(([method, path, purpose, auth, status, request, response]) => ({ method, path, purpose, auth, status: status as Status, request, response }));

function StatusBadge({ value }: { value: Status }) { return <span className={`docs-status ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>; }
function ApiCard({ api }: { api: Api }) { return <article className="api-card"><div className="api-heading"><span className="method">{api.method}</span><code>/api/v1{api.path}</code><StatusBadge value={api.status} /></div><p>{api.purpose}</p><div className="api-auth"><LockKeyhole size={14} /> {api.auth}</div><details><summary>Request & response examples <ChevronRight size={15} /></summary><div className="code-grid"><div><small>REQUEST</small><pre>{api.request}</pre></div><div><small>RESPONSE</small><pre>{api.response}</pre></div></div></details></article>; }

export function DocumentationPage() {
  const groups = [["Platform & identity", apis.slice(0, 9)], ["Mission, vessel & records", apis.slice(9, 15)], ["Environment, models & demo", apis.slice(15, 26)], ["Vessel-aware route governance", apis.slice(26, 35)], ["Safety, evidence & operations", apis.slice(35)]] as const;
  const links = [[Layers3,"Architecture","System boundaries"],[Radio,"Data Sources","Provider provenance"],[ShipWheel,"Vessel-Aware Planning","Human route review"],[CheckCircle2,"Implementation Status","What works today"],[Sparkles,"Live Demo","Offline ML example"],[Database,"Evidence","Code-grounded facts"]];
  return <main className="docs-shell"><header className="docs-header"><a className="brand" href="#overview"><span>◒</span> KURMESH <small>DOCUMENTATION</small></a><nav><a href="#architecture">Architecture</a><a href="#api-reference">API reference</a><a href="#evidence">Evidence</a><a className="demo-link" href="#live-demo">Live demo <ArrowRight size={15} /></a></nav></header>
    <section id="overview" className="hero"><div><p className="eyebrow">POLAR MARITIME DECISION SUPPORT</p><h1>Clear evidence for<br /><em>human</em> route decisions.</h1><p className="hero-copy">KURMESH is a human-in-the-loop foundation for polar maritime operations. It preserves the separation between data, advisory records and a human decision.</p><div className="hero-actions"><a href="#api-reference" className="primary">Explore the API <ArrowRight size={17} /></a><a href="#implementation-status" className="quiet">View implementation status</a></div></div><div className="polar-orb" aria-hidden="true"><div className="orb-glow" /><span className="orb-label">SOUTHERN<br />OCEAN</span><i className="orb-line line-a" /><i className="orb-line line-b" /><i className="orb-dot" /></div></section>
    <section className="quick-links" aria-label="Documentation sections">{links.map(([Icon, label, sub]) => <a key={String(label)} href={`#${String(label).toLowerCase().replaceAll(" ", "-")}`}><Icon size={19} /><span><b>{String(label)}</b><small>{String(sub)}</small></span><ChevronRight size={17} /></a>)}</section>
    <section id="architecture" className="doc-section"><div className="section-kicker">01 / ARCHITECTURE</div><h2>Designed to make authority visible.</h2><p className="lede">The system records inputs and governed decisions. Neither models, provider adapters, routing persistence nor workers can approve or execute a route.</p><div className="architecture"><div><span>INPUTS</span><b>Provider adapters</b><p>Normalize sourced sea-ice, weather and ocean observations.</p></div><ArrowRight /><div><span>EVIDENCE</span><b>PostGIS + provenance</b><p>Stores validated observations, records and append-only audit events.</p></div><ArrowRight /><div><span>GOVERNANCE</span><b>Human review</b><p>Independent operator review and approval are separate actions.</p></div></div></section>
    <section id="data-sources" className="doc-section split"><div><div className="section-kicker">02 / DATA SOURCES</div><h2>Opt-in providers with traceable status.</h2><p className="lede">Adapters only return normalized observations. Values are persisted only for <b>LIVE</b>, <b>STALE</b> or <b>DEGRADED</b>; unavailable and error outcomes contain no data.</p></div><div className="source-list"><div><b>NOAA / NSIDC G10016</b><span>Antarctic daily sea-ice concentration · 25 km · EPSG:3412</span><StatusBadge value="IMPLEMENTED" /></div><div><b>NOAA GFS</b><span>0.25° weather forecast: wind, air temperature, sea-level pressure</span><StatusBadge value="IMPLEMENTED" /></div><div><b>Copernicus Marine</b><span>Global ocean currents and potential temperature via Toolbox subset API</span><StatusBadge value="IMPLEMENTED" /></div></div></section>
    <section id="vessel-aware-planning" className="doc-section planning"><div className="section-kicker">03 / VESSEL-AWARE PLANNING</div><h2>Route records are not route authority.</h2><div className="planning-grid"><div><MapPinned size={22} /><b>Vessel & mission context</b><p>Vessels, missions and operational constraints are explicit API records.</p></div><div><Anchor size={22} /><b>Submitted candidates</b><p>GeoJSON route candidates are validated and stored; no route is calculated by these endpoints.</p></div><div><CheckCircle2 size={22} /><b>Separated decisions</b><p>An operator/admin reviewer and a different approver must act before a route becomes approved or rejected.</p></div></div><p className="safety-note">Safety boundary: the mission owner cannot review or approve their own route without admin authority.</p></section>
    <section id="implementation-status" className="doc-section"><div className="section-kicker">04 / IMPLEMENTATION STATUS</div><h2>Honest scope, at a glance.</h2><div className="status-grid"><div><StatusBadge value="IMPLEMENTED" /><b>Foundation & governed workflows</b><p>Flask API, authentication, PostGIS schema, audit events, environmental adapters, persistence APIs and human route review/approval.</p></div><div><StatusBadge value="IN DEVELOPMENT" /><b>Simulation execution</b><p>Simulation requests are persisted as PENDING records. No connected simulation worker is implemented.</p></div><div><StatusBadge value="FUTURE" /><b>Operational routing & automated execution</b><p>No API calculates routes, executes a route, or uses ML to approve a route. Those capabilities are intentionally absent.</p></div></div></section>
    <section id="live-demo" className="doc-section demo"><div><div className="section-kicker">05 / LIVE DEMO</div><h2>Offline iceberg model, carefully bounded.</h2><p className="lede">A public demo endpoint accepts a frozen feature vector and returns a 24-hour projected iceberg displacement in EPSG:3412. Its response is explicitly <b>OFFLINE_DEMO_ONLY</b> and cannot approve or execute a route.</p><a href="#api-reference" className="quiet">See the demo API <ArrowRight size={16} /></a></div><div className="demo-code"><small>POST /api/v1/demo/ml/iceberg/predict</small><pre>{'{\n  "status": "OFFLINE_DEMO_ONLY",\n  "forecast_horizon": "24 hours",\n  "target_crs": "EPSG:3412"\n}'}</pre></div></section>
    <section id="api-reference" className="doc-section api-section"><div className="section-kicker">06 / API REFERENCE</div><h2>All implemented HTTP endpoints.</h2><p className="lede">Base URL: <code>/api/v1</code>. Protected endpoints expect <code>Authorization: Bearer &lt;token&gt;</code>. Expand any card for a minimal request and response example.</p>{groups.map(([title, items]) => <div className="api-group" key={title}><h3>{title}</h3>{items.map((api) => <ApiCard api={api} key={`${api.method}-${api.path}`} />)}</div>)}</section>
    <section id="github" className="doc-section compact"><ClipboardList size={24} /><div><div className="section-kicker">07 / GITHUB</div><h2>Repository-first documentation.</h2><p>This hub is derived from the Flask blueprints, React client, provider adapters, schemas, tests and README in this repository.</p><a className="repo-link" href="https://github.com/sairajsachinpatil/kurmesh" target="_blank" rel="noreferrer">Open the KURMESH repository <ArrowRight size={15} /></a></div></section>
    <section id="evidence" className="doc-section evidence"><div><div className="section-kicker">08 / EVIDENCE</div><h2>What this documentation is based on.</h2></div><div className="evidence-grid"><div><b>API blueprints</b><span>Health, application, workflow and ML demo routes under <code>backend/app/api/v1</code>.</span></div><div><b>Provider modules</b><span>NOAA/NSIDC, NOAA GFS and Copernicus adapters plus normalized ingestion contract.</span></div><div><b>Safety controls</b><span>Role checks, mission ownership, review/approver separation, validation and append-only audit creation.</span></div></div></section>
    <footer><span>KURMESH · Polar maritime decision support</span><span>Built around human authority and traceable evidence.</span></footer>
  </main>;
}
